name: Build Marp Slides

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Clean docs folder
        run: rm -rf docs && mkdir -p docs

      - name: Build Marp presentations
        run: npx marp -I md --html --allow-local-files -o docs

      - name: Commit generated HTML
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: rebuild Marp slides"
          file_pattern: docs/**
